matrix:
  include:
    - language: java
      dist: bionic
      jdk:
        - oraclejdk11
      before_script:
        - cd backend

    - language: node_js
      dist: bionic
      node_js:
        - 12
      before_script:
        - cd frontend
      script:
        - npm install
        - npm test