matrix:
  include:
    - language: java
      dist: bionic
      jdk:
        - oraclejdk9
      before_script:
        - cd backend
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

    - language: node_js
      dist: bionic
      node_js:
        - 12
      before_script:
        - cd frontend
      script:
        - npm install
        - npm test