language: java
dist: bionic
before_script:
  - cd backend
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - redis-tools
      - redis-server
      
      
language: node_js
dist: bionic
before_script:
  - cd frontend
